# Data Wrangling

**Major Work in Progress**

- 90\% of data work is "wrangling" raw data files into something we can actually work with

There are perhaps 5 common tasks that most data analysis will require some combination of: 
1. Importing data (from an external source)
2. Merging data (from multiple sources)
3. Tidying data (transforming it to a useful structure)
4. Subsetting data (for conditional analysis)
5. Summarizing data (in summary statistics and plots)

## Packages

All of the tasks in this section can be undertaken with base `R` commands. However, several packages make these tasks much more efficient and intuitive to understand and document. 
- `dplyr` 
- `tidyr`
- `readr` 


## Importing Data

`getwd()`
`setwd()`
`list.files()`
`list.dirs()`


## Merging Data

- A simple merge 


## Using the `%>%` "Pipe" Operator



## Subsetting 

Objects are "*indexed*" by their `[row#, column#]` coordinates.

`df[ , ]`
`df[2,]`
`df[c(1,3,4),]`
`df[2:7,]`
`df[ ,3]`

`$` $\implies$: return all values of column named as a vector
`df[2,3]`

# missing data

`is.na()`